/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ColunistasRouteImport } from './routes/colunistas'
import { Route as SetupAdminRouteImport } from './routes/setup-admin'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ColunistaSlugRouteImport } from './routes/colunista.$slug'
import { Route as NoticiaSlugRouteImport } from './routes/noticia.$slug'
import { Route as AuthenticatedAdminNovaRouteImport } from './routes/_authenticated/admin.nova'
import { Route as AuthenticatedAdminEditIdRouteImport } from './routes/_authenticated/admin.edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ColunistasRoute = ColunistasRouteImport.update({
  id: '/colunistas',
  path: '/colunistas',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup-admin',
  path: '/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ColunistaSlugRoute = ColunistaSlugRouteImport.update({
  id: '/colunista/$slug',
  path: '/colunista/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiaSlugRoute = NoticiaSlugRouteImport.update({
  id: '/noticia/$slug',
  path: '/noticia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminNovaRoute = AuthenticatedAdminNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEditIdRoute =
  AuthenticatedAdminEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colunistas': typeof ColunistasRoute
  '/setup-admin': typeof SetupAdminRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/colunista/$slug': typeof ColunistaSlugRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
  '/admin/nova': typeof AuthenticatedAdminNovaRoute
  '/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colunistas': typeof ColunistasRoute
  '/setup-admin': typeof SetupAdminRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/colunista/$slug': typeof ColunistaSlugRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
  '/admin/nova': typeof AuthenticatedAdminNovaRoute
  '/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/colunistas': typeof ColunistasRoute
  '/setup-admin': typeof SetupAdminRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/colunista/$slug': typeof ColunistaSlugRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
  '/_authenticated/admin/nova': typeof AuthenticatedAdminNovaRoute
  '/_authenticated/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/colunistas'
    | '/setup-admin'
    | '/admin'
    | '/categoria/$slug'
    | '/colunista/$slug'
    | '/noticia/$slug'
    | '/admin/nova'
    | '/admin/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/colunistas'
    | '/setup-admin'
    | '/admin'
    | '/categoria/$slug'
    | '/colunista/$slug'
    | '/noticia/$slug'
    | '/admin/nova'
    | '/admin/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/colunistas'
    | '/setup-admin'
    | '/_authenticated/admin'
    | '/categoria/$slug'
    | '/colunista/$slug'
    | '/noticia/$slug'
    | '/_authenticated/admin/nova'
    | '/_authenticated/admin/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ColunistasRoute: typeof ColunistasRoute
  SetupAdminRoute: typeof SetupAdminRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ColunistaSlugRoute: typeof ColunistaSlugRoute
  NoticiaSlugRoute: typeof NoticiaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colunistas': {
      id: '/colunistas'
      path: '/colunistas'
      fullPath: '/colunistas'
      preLoaderRoute: typeof ColunistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-admin': {
      id: '/setup-admin'
      path: '/setup-admin'
      fullPath: '/setup-admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colunista/$slug': {
      id: '/colunista/$slug'
      path: '/colunista/$slug'
      fullPath: '/colunista/$slug'
      preLoaderRoute: typeof ColunistaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticia/$slug': {
      id: '/noticia/$slug'
      path: '/noticia/$slug'
      fullPath: '/noticia/$slug'
      preLoaderRoute: typeof NoticiaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/nova': {
      id: '/_authenticated/admin/nova'
      path: '/nova'
      fullPath: '/admin/nova'
      preLoaderRoute: typeof AuthenticatedAdminNovaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/edit/$id': {
      id: '/_authenticated/admin/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminEditIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminNovaRoute: typeof AuthenticatedAdminNovaRoute
  AuthenticatedAdminEditIdRoute: typeof AuthenticatedAdminEditIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminNovaRoute: AuthenticatedAdminNovaRoute,
  AuthenticatedAdminEditIdRoute: AuthenticatedAdminEditIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ColunistasRoute: ColunistasRoute,
  SetupAdminRoute: SetupAdminRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ColunistaSlugRoute: ColunistaSlugRoute,
  NoticiaSlugRoute: NoticiaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
